// Lab-Content.js - Comprehensive repository of hands-on code for all topics

class LabSystem {
    constructor() {
        this.baseColabUrl = "https://colab.research.google.com/";
    }

    getLabContent(topicId) {
        // 1. Try to find specific hand-crafted content
        if (this.specificLabs[topicId]) {
            return this.specificLabs[topicId];
        }

        // 2. Fallback: Generate relevant template code based on keywords
        return this.generateTemplateLab(topicId);
    }

    generateTemplateLab(topicId) {
        let structure = (typeof comprehensiveCourseStructure !== 'undefined') ? comprehensiveCourseStructure : null;
        let topicTitle = "";

        if (structure) {
            // Find topic title
            for (const module of structure.modules) {
                const topic = module.topics.find(t => t.id === topicId);
                if (topic) {
                    topicTitle = topic.title.toLowerCase();
                    break;
                }
            }
        }

        const keywords = {
            // --- Python Basics ---
            'variable': { c: `age = 25\ncrop = "Wheat"\nprice = 15.50\nprint(f"{crop} is sold at \${price}/kg")`, d: "Variable assignment example." },
            'operator': { c: `a = 10\nb = 3\nprint(f"Addition: {a+b}, Modulo: {a%b}, Power: {a**b}")`, d: "Basic arithmetic operations." },
            'loop': { c: `temperatures = [22, 24, 19, 25]\nfor t in temperatures:\n    if t > 23: print(f"High Temp: {t}")`, d: "Iterating through data." },
            'condition': { c: `moisture = 45\nif moisture < 30: print("Start Irrigation")\nelse: print("Moisture sufficient")`, d: "Decision making logic." },
            'function': { c: `def calc_yield(area, rate):\n    return area * rate\n\nprint(f"Total Yield: {calc_yield(10, 4.5)} tons")`, d: "Modular code with functions." },
            'list': { c: `crops = ["Rice", "Wheat"]\ncrops.append("Maize")\nprint(f"First crop: {crops[0]}")`, d: "List manipulation." },
            'dictionary': { c: `farm = {"size": 50, "location": "Bangalore"}\nprint(f"Farm Size: {farm['size']} acres")`, d: "Key-Value data structures." },
            'string': { c: `text = "  Agriculture AI  "\nprint(text.strip().lower().replace("ai", "intelligence"))`, d: "String processing methods." },
            'file': { c: `with open("data.txt", "w") as f:\n    f.write("Log Entry 1")\n\nprint("File written successfully.")`, d: "File I/O operations." },
            'setup': { c: `import sys\nprint(f"Python Version: {sys.version}")`, d: "Environment Check." },
            'install': { c: `!pip install pandas numpy scikit-learn`, d: "Library Installation." },

            // --- Data Science ---
            'numpy': { c: `import numpy as np\narr = np.array([1, 2, 3, 4])\nprint(f"Mean: {np.mean(arr)}, Max: {np.max(arr)}")`, d: "NumPy array operations." },
            'matrix': { c: `import numpy as np\nm1 = np.array([[1,2],[3,4]])\nm2 = np.array([[5,6],[7,8]])\nprint(np.dot(m1, m2))`, d: "Linear algebra with NumPy." },
            'pandas': { c: `import pandas as pd\ndf = pd.DataFrame({'Date': ['Mon','Tue'], 'Rain': [10, 0]})\nprint(df.describe())`, d: "Pandas DataFrame basics." },
            'dataframe': { c: `import pandas as pd\ndf = pd.DataFrame({'Val': [1, 2, 3]})\nfiltered = df[df['Val'] > 1]\nprint(filtered)`, d: "DataFrame filtering." },
            'visualization': { c: `import matplotlib.pyplot as plt\nplt.plot([1,2,3], [10,20,15])\nplt.title("Growth Curve")\nplt.show()`, d: "Basic plotting (Matplotlib/Seaborn)." },
            'plot': { c: `import matplotlib.pyplot as plt\nplt.hist([1,1,2,3,4,4,4,5])\nplt.title("Distribution")\nplt.show()`, d: "Statistical plots." },
            'missing': { c: `import pandas as pd\nimport numpy as np\ndf = pd.DataFrame({'A': [1, np.nan, 3]})\nprint(df.fillna(0))`, d: "Handling NaN values." },
            'aggregation': { c: `import pandas as pd\ndf = pd.DataFrame({'Cat':['A','A','B'], 'Val':[1,2,3]})\nprint(df.groupby('Cat').sum())`, d: "Grouping and aggregation." },

            // --- Machine Learning ---
            'workflow': { c: `print("1. Collect Data\\n2. Preprocess\\n3. Train Model\\n4. Evaluate")`, d: "Standard ML Pipeline steps." },
            'supervised': { c: `# X = Inputs, y = Labels\nfrom sklearn.linear_model import LinearRegression\nmodel = LinearRegression().fit([[0], [1], [2]], [0, 2, 4])\nprint(model.predict([[3]]))`, d: "Supervised learning example." },
            'split': { c: `from sklearn.model_selection import train_test_split\nimport numpy as np\nX, y = np.arange(10).reshape(-1, 1), np.arange(10)\nX_train, X_test, y_train, y_test = train_test_split(X, y)\nprint(f"Train size: {len(X_train)}")`, d: "Splitting datasets." },
            'regression': { c: `from sklearn.linear_model import LinearRegression\n# Predict Yield based on Fertilizer\nmodel = LinearRegression()\nmodel.fit([[10], [20], [30]], [1.5, 2.5, 3.5])\nprint(f"Coeff: {model.coef_}")`, d: "Linear, Ridge, or Lasso regression." },
            'classification': { c: `from sklearn.tree import DecisionTreeClassifier\nclf = DecisionTreeClassifier()\nclf.fit([[0,0], [1,1]], [0, 1])\nprint(f"Class: {clf.predict([[0.5, 0.5]])}")`, d: "Classification logic." },
            'tree': { c: `from sklearn.tree import DecisionTreeRegressor\nmodel = DecisionTreeRegressor(max_depth=3)\nprint("Tree model initialized.")`, d: "Decision Tree structure." },
            'evaluation': { c: `from sklearn.metrics import mean_squared_error\nactual = [10, 20]\npred = [12, 18]\nprint(f"MSE: {mean_squared_error(actual, pred)}")`, d: "Performance metrics." },
            'overfitting': { c: `# High Variance Example\nprint("Train Accuracy: 99%\\nTest Accuracy: 60%\\nDiagnosis: Overfitting")`, d: "Demonstrating overfitting concepts." },
            'logistic': { c: `from sklearn.linear_model import LogisticRegression\nmodel = LogisticRegression()\nprint("Logistic Regression Ready.")`, d: "Binary classification." },

            // --- Module 3 Specifics ---
            'feature': { c: `from sklearn.preprocessing import StandardScaler\nscaler = StandardScaler()\nscaled = scaler.fit_transform([[100], [200], [150]])\nprint(scaled)`, d: "Feature engineering/scaling." },
            'weather': { c: `import pandas as pd\ndf = pd.DataFrame({'Max_Temp':[30,32], 'Min_Temp':[20,22]})\ndf['Diff'] = df['Max_Temp'] - df['Min_Temp']\nprint(df)`, d: "Weather data processing." },
            'image': { c: `import cv2\n# img = cv2.imread('leaf.jpg')\nprint("OpenCV loaded for image processing.")`, d: "Image processing (OpenCV)." },
            'cnn': { c: `import tensorflow as tf\nmodel = tf.keras.Sequential([tf.keras.layers.Conv2D(32, (3,3), input_shape=(64,64,3))])\nmodel.summary()`, d: "Convolutional Neural Network base." },
            'time series': { c: `from statsmodels.tsa.seasonal import seasonal_decompose\n# Mock decomposition\nprint("Trend: Increasing\\nSeasonality: Annual")`, d: "Time series components." },
            'outlier': { c: `import seaborn as sns\n# sns.boxplot(data=[1,2,50,2,3])\nprint("Boxplot shows outliers.")`, d: "Outlier detection viz." },
            'clustering': { c: `from sklearn.cluster import KMeans\nprint("KMeans Clustering Ready.")`, d: "Unsupervised clustering." },
            'yield': { c: `from sklearn.ensemble import RandomForestRegressor\nrf = RandomForestRegressor(n_estimators=100)\nprint("Yield model ready")`, d: "Crop yield prediction." },
            'ensemble': { c: `from sklearn.ensemble import VotingClassifier\nprint("Ensemble learning")`, d: "Combining models." },
            'boosting': { c: `from sklearn.ensemble import GradientBoostingRegressor\nprint("Gradient Boosting")`, d: "Boosting algorithms." },
            'transfer': { c: `from tensorflow.keras.applications import ResNet50\nbase = ResNet50(weights='imagenet')\nprint("Transfer learning")`, d: "Pre-trained models." },
            'arima': { c: `from statsmodels.tsa.arima.model import ARIMA\nmodel = ARIMA(data, order=(1,1,1))\nprint(model.fit().forecast(5))`, d: "Time series forecasting." },
            'yolo': { c: `# YOLO object detection\nprint("Real-time detection")`, d: "YOLO algorithm." },
            'ndvi': { c: `nir, red = 0.6, 0.1\nndvi = (nir-red)/(nir+red)\nprint(f"NDVI: {ndvi:.2f}")`, d: "Vegetation index." },
            'grid': { c: `from sklearn.model_selection import GridSearchCV\nparam_grid = {'n_estimators': [50,100]}\nprint("Grid search")`, d: "Hyperparameter tuning." },
            'pipeline': { c: `from sklearn.pipeline import Pipeline\npipe = Pipeline([('scaler', scaler), ('model', model)])`, d: "ML pipeline." },
            'deploy': { c: `import pickle\nwith open('model.pkl', 'wb') as f:\n    pickle.dump(model, f)`, d: "Save model." },
            'api': { c: `from flask import Flask\napp = Flask(__name__)\n@app.route('/predict')\ndef predict():\n    return {'result': 1}`, d: "REST API." }
        };

        // Scan keys
        for (const [key, val] of Object.entries(keywords)) {
            if (topicTitle.includes(key)) {
                return {
                    code: val.c,
                    description: val.d,
                    colabUrl: this.baseColabUrl
                };
            }
        }

        // Generic Fallback based on Module
        if (topicId.startsWith('m1')) return { code: `# Generic Python Sandbox\nprint("Hello Agriculture AI!")`, description: "Python Practice", colabUrl: this.baseColabUrl };
        if (topicId.startsWith('m2')) return { code: `import pandas as pd\nimport numpy as np\n# Ready for Data Science`, description: "Data Science Sandbox", colabUrl: this.baseColabUrl };

        return {
            code: "# No specific code template available for this topic.\n# Try exploring the concepts in a blank notebook!",
            description: "Standard Python Environment",
            colabUrl: this.baseColabUrl
        };
    }

    get specificLabs() {
        return {
            // --- MODULE 1: Python Fundamentals ---
            // --- MODULE 1: Python Fundamentals ---
            'm1-t1': { code: `# --- SAMPLE INPUT ---\n# crow_speed = 50 km/h (Fast!)\n\n# --- ILLUSTRATION ---\ncrow_speed = 50\n\nif crow_speed > 40:\n    print("Shout NOW!")\nelse:\n    print("Wait...")\n\n# --- OUTPUT INTERPRETATION ---\n# Output: "Shout NOW!"\n# Why? Because 50 > 40. The logic detects a threat.`, description: "Smart Scarecrow: Logic based on speed.", colabUrl: "https://colab.research.google.com/" },
            'm1-t2': { code: `# --- SAMPLE INPUT ---\n# Supervised: Labels provided. Unsupervised: Just raw data.\n\n# --- ILLUSTRATION ---\n# 1. Supervised Learning (Teacher)\nlabels = {"Red_Fruit": "Apple", "Yellow_Fruit": "Banana"}\nprint(f"Supervised: Red Fruit is {labels['Red_Fruit']}")\n\n# 2. Unsupervised Learning (Discovery)\nfruits = [50, 10, 20, 60] # Sizes in mm\nfruits.sort() # Grouping small with small\nprint(f"Unsupervised Sorting: {fruits}")\n\n# --- OUTPUT INTERPRETATION ---\n# Supervised uses a lookup (Apples). Unsupervised finds order (Sorting).`, description: "Coding the difference between learning paradigms.", colabUrl: "https://colab.research.google.com/" },
            'm1-t3': { code: `# --- SAMPLE INPUT ---\n# Current Year = 2024\n\n# --- ILLUSTRATION ---\ncurrent_year = 2024\nai_birth_year = 1950\n\nage = current_year - ai_birth_year\nprint(f"AI is {age} years old today.")\n\n# --- OUTPUT INTERPRETATION ---\n# Calculates the age of the field of Artificial Intelligence.`, description: "Timeline calculator for AI history.", colabUrl: "https://colab.research.google.com/" },
            'm1-t4': { code: `# --- SAMPLE INPUT ---\n# Pest = "Locust"\n\n# --- ILLUSTRATION ---\npest_type = "Locust"\n\n# Expert System Rule\nif pest_type == "Locust":\n    action = "Activate Drones"\nelif pest_type == "Aphid":\n    action = "Release Ladybugs"\nelse:\n    action = "Monitor"\n\nprint(f"Recommended Action: {action}")\n\n# --- OUTPUT INTERPRETATION ---\n# Output: Activate Drones\n# Shows how AI maps observations to decisions.`, description: "Simple Expert System for Pest Control.", colabUrl: "https://colab.research.google.com/" },
            'm1-t5': { code: `# --- SAMPLE INPUT ---\n# Skills List\n\n# --- ILLUSTRATION ---\nmy_skills = ["Python", "Biology", "Data Analysis"]\nrequired = ["Python", "Cloud"]\n\nmatch = set(my_skills).intersection(required)\nprint(f"Matching Job Skills: {match}")\n\n# --- OUTPUT INTERPRETATION ---\n# Output: {'Python'}\n# Demonstrates skill matching for AgriTech roles.`, description: "AgriTech Resume Skill Matcher.", colabUrl: "https://colab.research.google.com/" },
            'm1-t6': { code: `# --- SAMPLE INPUT ---\n# Field: 100m x 50m\n\n# --- ILLUSTRATION ---\nlength = 100\nwidth = 50\n\narea = length * width\nperimeter = 2 * (length + width)\n\nprint(f"Farm Area: {area} sqm")\nprint(f"Fence Needed: {perimeter} m")\n\n# --- OUTPUT INTERPRETATION ---\n# Basic Geometry calculations essential for land management.`, description: "Farm Geometry Calculator.", colabUrl: "https://colab.research.google.com/" },
            'm1-t7': { code: `# --- SAMPLE INPUT ---\n# Yields (tons/acre): [4.5, 5.0, 5.2, 4.8, 8.0]\n\n# --- ILLUSTRATION ---\nimport numpy as np\nyields = [4.5, 5.0, 5.2, 4.8, 8.0]\n\nprint(f"Mean: {np.mean(yields)}")   # Average\nprint(f"Median: {np.median(yields)}") # Middle value\n\n# --- OUTPUT INTERPRETATION ---\n# Mean = 5.5, Median = 5.0\n# The Mean is higher because the outlier (8.0) pulls it up.`, description: "Calculate basic farm statistics.", colabUrl: "https://colab.research.google.com/" },
            'm1-t8': { code: `# --- SAMPLE INPUT ---\n# Fields (Acres): [[10, 5], [8, 8]]\n# Prices ($/acre): [20, 30]\n\n# --- ILLUSTRATION ---\nimport numpy as np\nfields = np.array([[10, 5], [8, 8]])\nprices = np.array([20, 30])\n\n# Dot Product: (10*20 + 5*30) ...\nprint(f"Revenue: {np.dot(fields, prices)}")\n\n# --- OUTPUT INTERPRETATION ---\n# Output: [350 400]\n# Farm A made $350, Farm B made $400.`, description: "Calculate revenue using dot product.", colabUrl: "https://colab.research.google.com/" },
            'm1-t10': { code: `# --- SAMPLE INPUT ---\n# Simulated IoT Pulse: Random(60-100)\n\n# --- ILLUSTRATION ---\nimport time\nimport random\n\nwhile True:\n    pulse = random.randint(60, 100)\n    print(f"Sending Pulse: {pulse}")\n    if pulse < 50: \n        print("ALERT: Sensor Failure")\n    time.sleep(1)\n    break # Stop after one loop for demo\n\n# --- OUTPUT INTERPRETATION ---\n# Output: Sending Pulse: 85\n# Status: Normal operation (No Alert).`, description: "Simulating IoT Data Stream.", colabUrl: "https://colab.research.google.com/" },
            'm1-t11': { code: `# --- SAMPLE INPUT ---\n# None (Static String)\n\n# --- ILLUSTRATION ---\nprint("Hello Farm")\n# Press Shift+Enter to run\n\n# --- OUTPUT INTERPRETATION ---\n# Output: Hello Farm\n# This confirms your Python environment is working.`, description: "Your first Python command.", colabUrl: "https://colab.research.google.com/" },
            'm1-t12': { code: `# --- SAMPLE INPUT ---\n# Initial Harvest = 50\n\n# --- ILLUSTRATION ---\nharvest = 50\nprint(f"Harvest: {harvest}")\n\nharvest = 60 # Update variable\nprint(f"Updated Harvest: {harvest}")\n\n# --- OUTPUT INTERPRETATION ---\n# Output: 50 -> 60\n# Interpretation: Variables act as storage containers that can change.`, description: "Variables: Changing values over time.", colabUrl: "https://colab.research.google.com/" },
            'm1-t13': { code: `# --- SAMPLE INPUT ---\n# Moisture = 20% (Dry)\n# Rain Forecast = False\n\n# --- ILLUSTRATION ---\nsoil_moisture = 20\nrain_forecast = False\n\n# Both conditions must be met\nshould_water = (soil_moisture < 30) and (not rain_forecast)\nprint(f"Water Pump On? {should_water}")\n\n# --- OUTPUT INTERPRETATION ---\n# Output: True\n# Interpretation: It is dry and no rain is coming, so we MUST water.`, description: "Boolean Logic for Irrigation.", colabUrl: "https://colab.research.google.com/" },
            'm1-t14': { code: `# --- SAMPLE INPUT ---\n# Moisture = 15%\n\n# --- ILLUSTRATION ---\nmoisture = 15\nif moisture < 20:\n    print("⚠️ Critical! Water immediately!")\nelif moisture < 40:\n    print("💧 Water soon.")\nelse:\n    print("✅ Soil is happy.")\n\n# --- OUTPUT INTERPRETATION ---\n# Output: ⚠️ Critical!\n# Interpretation: Moisture is below the emergency threshold (20).`, description: "Control logic for smart irrigation systems.", colabUrl: "https://colab.research.google.com/" },
            'm1-t15': { code: `# --- SAMPLE INPUT ---\n# Crop List: Wheat, Rice, Maize\n\n# --- ILLUSTRATION ---\ncrops = ["Wheat", "Rice", "Maize"]\nfor crop in crops:\n    print(f"Harvesting {crop}...")\n\n# --- OUTPUT INTERPRETATION ---\n# Output: Harvesting Wheat... Rice... Maize\n# Interpretation: The loop iterates through every item in the list.`, description: "Loop through specific crops in your inventory.", colabUrl: "https://colab.research.google.com/" },
            'm1-t16': { code: `# --- SAMPLE INPUT ---\n# pH Level = 5.5\n\n# --- ILLUSTRATION ---\ndef check_soil(ph):\n    if ph < 7: return "Acidic (Add Lime)"\n    return "Neutral"\n\nprint(check_soil(5.5))\n\n# --- OUTPUT INTERPRETATION ---\n# Output: Acidic (Add Lime)\n# Interpretation: pH < 7 triggers the acidity correction logic.`, description: "Functions: Soil Checker.", colabUrl: "https://colab.research.google.com/" },
            'm1-t17': { code: `# --- SAMPLE INPUT ---\n# Inventory Dictionary\n\n# --- ILLUSTRATION ---\ninventory = {"Seeds": 50, "Fertilizer_Bags": 20}\nprint(f"Fertilizer Stock: {inventory['Fertilizer_Bags']}")\n\n# --- OUTPUT INTERPRETATION ---\n# Output: 20\n# Interpretation: Dictionaries allow fast lookup by 'Key' (Name).`, description: "Manage farm inventory using Python dictionaries.", colabUrl: "https://colab.research.google.com/" },
            'm1-t18': { code: `# --- SAMPLE INPUT ---\n# Label: "  Wheat Crop "\n\n# --- ILLUSTRATION ---\nlabel = "  Wheat Crop "\nclean = label.strip().upper()\nprint(f"'{clean}'")\n\n# --- OUTPUT INTERPRETATION ---\n# Output: 'WHEAT CROP'\n# Interpretation: Spaces removed (.strip) and converted to Uppercase (.upper).`, description: "String cleaning for data labels.", colabUrl: "https://colab.research.google.com/" },
            'm1-t19': { code: `# --- SAMPLE INPUT ---\n# Text: "Yield: 50 tons"\n\n# --- ILLUSTRATION ---\nwith open('log.txt', 'w') as f:\n    f.write("Yield: 50 tons")\n\nwith open('log.txt', 'r') as f:\n    print(f.read())\n\n# --- OUTPUT INTERPRETATION ---\n# Output: Yield: 50 tons\n# Interpretation: Data was successfully saved to disk and read back.`, description: "File Handling: Writing logs.", colabUrl: "https://colab.research.google.com/" },

            // --- MODULE 2: Data Science & ML ---
            'm2-t1': { code: `# --- SAMPLE INPUT ---\n# pH Levels: [6.5, 7.0, 5.5, 6.2, 6.8]\n\n# --- ILLUSTRATION ---\nimport numpy as np\nph_levels = np.array([6.5, 7.0, 5.5, 6.2, 6.8])\nprint(f"Average pH: {np.mean(ph_levels)}")\nprint(f"High Acidity Count: {np.sum(ph_levels < 6.0)}")\n\n# --- OUTPUT INTERPRETATION ---\n# Average pH: 6.4\n# High Acidity Count: 1 (Only 5.5 is < 6.0).`, description: "Analyze soil acidity with NumPy.", colabUrl: "https://colab.research.google.com/" },
            'm2-t2': { code: `# --- SAMPLE INPUT ---\n# Grid (2x2): [[40, 50], [35, 45]]\n\n# --- ILLUSTRATION ---\nimport numpy as np\nyields = np.array([[40, 50], [35, 45]])\nprint(f"Original Shape: {yields.shape}")\nprint(f"Transposed:\n{yields.T}")\n\n# --- OUTPUT INTERPRETATION ---\n# Transposed:\n# [[40 35]\n#  [50 45]]\n# Rows became Columns (Rotated the field grid).`, description: "Matrix Transpose for Field Grids.", colabUrl: "https://colab.research.google.com/" },
            'm2-t3': { code: `# --- SAMPLE INPUT ---\n# Heights: [10, 20, 15] cm\n\n# --- ILLUSTRATION ---\nimport numpy as np\nheights = np.array([10, 20, 15])\n# Add 5cm to all (Broadcasting)\nprint(f"New Heights: {heights + 5}")\n\n# --- OUTPUT INTERPRETATION ---\n# New Heights: [15 25 20]\n# The operation '+5' was applied to EVERY element automatically.`, description: "Broadcasting operations.", colabUrl: "https://colab.research.google.com/" },
            'm2-t4': { code: `# --- SAMPLE INPUT ---\n# Weights: [200, 210, 190, 500]\n\n# --- ILLUSTRATION ---\nimport numpy as np\nweights = np.array([200, 210, 190, 500])\nprint(f"Mean: {np.mean(weights):.2f}")\nprint(f"Std Dev: {np.std(weights):.2f}")\n\n# --- OUTPUT INTERPRETATION ---\n# Mean: 275.00, Std Dev: 130.29\n# High Std Dev indicates high variation (The 500g implies an outlier).`, description: "Statistical summary of harvest.", colabUrl: "https://colab.research.google.com/" },
            'm2-t5': { code: `# --- SAMPLE INPUT ---\n# Dict: {'Crop':..., 'Yield':...}\n\n# --- ILLUSTRATION ---\nimport pandas as pd\ndata = {'Crop': ['Wheat', 'Rice'], 'Yield': [4.5, 6.0]}\ndf = pd.DataFrame(data)\nprint(df)\n\n# --- OUTPUT INTERPRETATION ---\n#     Crop  Yield\n# 0  Wheat    4.5\n# 1   Rice    6.0\n# A clean, table-like structure.`, description: "Create a basic storage DataFrame.", colabUrl: "https://colab.research.google.com/" },
            'm2-t6': { code: `# --- SAMPLE INPUT ---\n# Price Column needs update.\n\n# --- ILLUSTRATION ---\nimport pandas as pd\ndf = pd.DataFrame({'Crop': ['Wheat', 'Rice'], 'Price': [2000, 2500]})\n# Add new column\ndf['Revenue'] = df['Price'] * 10\nprint(df)\n\n# --- OUTPUT INTERPRETATION ---\n# Revenue column added: [20000, 25000]\n# We calculated derived data for the whole column at once.`, description: "Manipulate DataFrames to calculate revenue.", colabUrl: "https://colab.research.google.com/" },
            'm2-t7': { code: `# --- SAMPLE INPUT ---\n# Yields: [4.5, 6.2, 5.5]\n\n# --- ILLUSTRATION ---\nimport pandas as pd\ndf = pd.DataFrame({'Yield': [4.5, 6.2, 5.5]})\nprint(df.describe())\n\n# --- OUTPUT INTERPRETATION ---\n# Count: 3.0, Mean: 5.4, Std: 0.85...\n# Provides a quick statistical snapshot of the dataset.`, description: "Quick statistical insights.", colabUrl: "https://colab.research.google.com/" },
            'm2-t8': { code: `# --- SAMPLE INPUT ---\n# DataFrame with Yields 4 and 8.\n\n# --- ILLUSTRATION ---\nimport pandas as pd\ndf = pd.DataFrame({'Crop': ['A', 'B'], 'Yield': [4, 8]})\nhigh_yield = df[df['Yield'] > 5]\nprint(high_yield)\n\n# --- OUTPUT INTERPRETATION ---\n#   Crop  Yield\n# 1    B      8\n# Only Crop B remains. The Sieve filtered out A (4 < 5).`, description: "Filtering data (The Sieve).", colabUrl: "https://colab.research.google.com/" },
            'm2-t9': { code: `# --- SAMPLE INPUT ---\n# Data with NaN (Missing)\n\n# --- ILLUSTRATION ---\nimport pandas as pd\nimport numpy as np\ndf = pd.DataFrame({'Val': [1, np.nan, 2]})\nprint(df.fillna(0))\n\n# --- OUTPUT INTERPRETATION ---\n#    Val\n# 0  1.0\n# 1  0.0  <-- Replaced NaN\n# 2  2.0`, description: "Handling missing values.", colabUrl: "https://colab.research.google.com/" },
            'm2-t10': { code: `# --- SAMPLE INPUT ---\n# Crop Groups: A, A, B\n\n# --- ILLUSTRATION ---\nimport pandas as pd\ndf = pd.DataFrame({'Crop': ['A', 'A', 'B'], 'Y': [1, 2, 5]})\nprint(df.groupby('Crop')['Y'].mean())\n\n# --- OUTPUT INTERPRETATION ---\n# Crop\n# A    1.5\n# B    5.0\n# 'A' was averaged (1+2)/2.`, description: "Grouping and Aggregation.", colabUrl: "https://colab.research.google.com/" },
            'm2-t11': { code: `# --- SAMPLE INPUT ---\n# Rain Data: [50, 45, 60] mm\n\n# --- ILLUSTRATION ---\nimport matplotlib.pyplot as plt\n# Bar Chart: Categorical Data\nplt.bar(['Jan', 'Feb', 'Mar'], [50, 45, 60], color='green')\nplt.title("Monthly Rainfall (mm)")\nplt.show()\n\n# --- OUTPUT INTERPRETATION ---\n# (Plot Window Appears)\n# A Green Bar Chart showing March as the tallest bar (wettest month).`, description: "Bar Chart: Comparing totals.", colabUrl: "https://colab.research.google.com/" },
            'm2-t12': { code: `# --- SAMPLE INPUT ---\n# Random Normal Data (Bell Curve)\n\n# --- ILLUSTRATION ---\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport numpy as np\ndata = np.random.normal(100, 10, 200)\n\n# 1. Histogram (Distribution)\nplt.hist(data, bins=10)\nplt.title("Yield Distribution")\nplt.show()\n\n# 2. Box Plot (Outliers)\nsns.boxplot(x=data)\nplt.title("Yield Outliers Check")\nplt.show()\n\n# --- OUTPUT INTERPRETATION ---\n# Histogram shows a bell shape centered at 100.\n# Box Plot shows a box with whiskers. Dots outside whiskers are outliers.`, description: "Histograms & Box Plots.", colabUrl: "https://colab.research.google.com/" },
            'm2-t13': { code: `# --- SAMPLE INPUT ---\n# Correlation Data: Rain vs Yield vs Pest\n\n# --- ILLUSTRATION ---\nimport seaborn as sns\nimport matplotlib.pyplot as plt\nimport pandas as pd\n\n# Correlation Heatmap\ndf = pd.DataFrame({'Rain': [10, 20, 30], 'Yield': [5, 15, 25], 'Pest': [50, 20, 10]})\nsns.heatmap(df.corr(), annot=True, cmap='coolwarm')\nplt.title("Feature Correlation Heatmap")\nplt.show()\n\n# --- OUTPUT INTERPRETATION ---\n# Red square between Rain/Yield (+1.0) -> Strong Friends.\n# Blue square between Pest/Yield (-1.0) -> Enemies.`, description: "Heatmaps for Correlation.", colabUrl: "https://colab.research.google.com/" },
            'm2-t14': { code: `# --- SAMPLE INPUT ---\n# None\n\n# --- ILLUSTRATION ---\nprint("Step 1: Get Data (Harvest Logs)")\nprint("Step 2: Clean Data (Remove Errors)")\nprint("Step 3: Train Model (Teach)")\nprint("Step 4: Predict (Future)")\n\n# --- OUTPUT INTERPRETATION ---\n# Text output listing the 4 main pillars of any ML project.`, description: "The Standard ML Workflow.", colabUrl: "https://colab.research.google.com/" },
            'm2-t15': { code: `# --- SAMPLE INPUT ---\n# None\n\n# --- ILLUSTRATION ---\nprint("Supervised: Here is a photo of Potato Blight.")\nprint("Unsupervised: Group these leaves by color.")\n\n# --- OUTPUT INTERPRETATION ---\n# Explains the difference: Supervised has labels (Teacher), Unsupervised does not (Discovery).`, description: "Paradigms of Learning.", colabUrl: "https://colab.research.google.com/" },
            'm2-t23': { code: `# --- SAMPLE INPUT ---\n# Spots Coverage: 60%\n\n# --- ILLUSTRATION ---\nfrom sklearn.linear_model import LogisticRegression\nimport numpy as np\n# 0=Healthy, 1=Diseased (Mock Data)\nX = np.array([[10], [50], [90], [20]]) # Spot coverage %\ny = np.array([0, 1, 1, 0])\nmodel = LogisticRegression()\nmodel.fit(X, y)\n\nprediction = model.predict([[60]])[0]\nprint(f"Prediction for 60% spots: {'Diseased' if prediction==1 else 'Healthy'}")\n\n# --- OUTPUT INTERPRETATION ---\n# Output: Diseased\n# Because 60% is closer to the diseased examples (50, 90) than healthy (10, 20).`, description: "Binary classification for plant health.", colabUrl: "https://colab.research.google.com/" },

            // --- MODULE 3: Advanced Applications ---
            // --- MODULE 3: Advanced Applications ---
            'm3-t1': { code: `# --- SAMPLE INPUT ---\n# Data = [10, 50, 90] (Wildly different scales)\n\n# --- ILLUSTRATION ---\nfrom sklearn.preprocessing import StandardScaler\nimport numpy as np\ndata = np.array([[10], [50], [90]])\nscaler = StandardScaler()\nprint(f"Scaled:\n{scaler.fit_transform(data)}")\n\n# --- OUTPUT INTERPRETATION ---\n# Output: [[-1.22], [0.0], [1.22]]\n# All values are now centered around 0.`, description: "Feature Scaling (Normalization).", colabUrl: "https://colab.research.google.com/" },
            'm3-t2': { code: `# --- SAMPLE INPUT ---\n# Random Training Data (100 samples)\n\n# --- ILLUSTRATION ---\nfrom sklearn.ensemble import RandomForestRegressor\nimport numpy as np\nX = np.random.rand(100, 3)\ny = np.random.rand(100)\nmodel = RandomForestRegressor()\nmodel.fit(X, y)\nprint("Random Forest trained on 100 samples.")\n\n# --- OUTPUT INTERPRETATION ---\n# Status: Trained.\n# The 'Forest' of decision trees has learned from the random data.`, description: "Train Random Forest for yield prediction.", colabUrl: "https://colab.research.google.com/" },
            'm3-t3': { code: `# --- SAMPLE INPUT ---\n# X=[1,2,3,4], Y=[1,4,9,16] (Exponential)\n\n# --- ILLUSTRATION ---\nimport numpy as np\nimport numpy.polynomial.polynomial as poly\nx = [1, 2, 3, 4]\ny = [1, 4, 9, 16]\ncoefs = poly.polyfit(x, y, 2)\nprint(f"Polynomial Coefficients: {coefs}")\n\n# --- OUTPUT INTERPRETATION ---\n# Output approximates x^2 (since 1^2=1, 2^2=4...)\n# The curve fits the 'bend' in data better than a straight line.`, description: "Fitting a curve (Polynomial Regression).", colabUrl: "https://colab.research.google.com/" },
            'm3-t4': { code: `# --- SAMPLE INPUT ---\n# Weather Data: Temps [30, 32, 29]\n\n# --- ILLUSTRATION ---\nimport pandas as pd\n# Mock Weather API response\ndata = {'Temp': [30, 32, 29], 'Rain': [0, 5, 10]}\ndf = pd.DataFrame(data)\nprint("Weather Data Loaded:")\nprint(df.mean())\n\n# --- OUTPUT INTERPRETATION ---\n# Temp: 30.33, Rain: 5.0\n# Aggregated weather statistics for the period.`, description: "Processing weather API data.", colabUrl: "https://colab.research.google.com/" },
            'm3-t5': { code: `# --- SAMPLE INPUT ---\n# Grid 10x10 with 3 layers (N, P, K)\n\n# --- ILLUSTRATION ---\nimport numpy as np\n# 3D Array: x, y, depth\nsoil_cube = np.zeros((10, 10, 3))\nprint(f"Soil Sample Shape: {soil_cube.shape}")\n\n# --- OUTPUT INTERPRETATION ---\n# (10, 10, 3)\n# Represents a physical block of soil data in 3 dimensions.`, description: "Representing 3D soil layers.", colabUrl: "https://colab.research.google.com/" },
            'm3-t6': { code: `# --- SAMPLE INPUT ---\n# NIR = 0.8, Red = 0.1 (Healthy Plant)\n\n# --- ILLUSTRATION ---\nimport numpy as np\nNIR = 0.8\nRed = 0.1\nNDVI = (NIR - Red) / (NIR + Red)\nprint(f"NDVI Health Index: {NDVI:.2f}")\n\n# --- OUTPUT INTERPRETATION ---\n# NDVI: 0.78\n# High value (close to 1) indicates very healthy vegetation.`, description: "Calculating NDVI manually.", colabUrl: "https://colab.research.google.com/" },
            'm3-t7': { code: `# --- SAMPLE INPUT ---\n# Image Shape: (64, 64, 3)\n\n# --- ILLUSTRATION ---\nfrom tensorflow.keras import layers, models\nmodel = models.Sequential()\nmodel.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(64, 64, 3)))\nmodel.add(layers.MaxPooling2D((2, 2)))\nmodel.summary()\nprint("CNN Feature Extraction Layer Built")\n\n# --- OUTPUT INTERPRETATION ---\n# Model Summary table appears.\n# Shows how the image size shrinks (MaxPooling) as features are extracted.`, description: "Build the feature extraction base of a CNN.", colabUrl: "https://colab.research.google.com/" },
            'm3-t8': { code: `# --- SAMPLE INPUT ---\n# Blank 10x10 Canvas\n\n# --- ILLUSTRATION ---\nimport numpy as np\nimport matplotlib.pyplot as plt\nimg = np.zeros((10, 10))\nimg[2:5, 3:6] = 1 # Draw a box\nplt.imshow(img, cmap='gray')\nplt.show()\n\n# --- OUTPUT INTERPRETATION ---\n# (Plot Window)\n# A white square appears on a black background.\n# Images are just grid of numbers!`, description: "Basic pixel manipulation.", colabUrl: "https://colab.research.google.com/" },
            'm3-t9': { code: `# --- SAMPLE INPUT ---\n# Concept of Edges\n\n# --- ILLUSTRATION ---\nfrom tensorflow.keras.layers import Conv2D\n# Filter/Kernel detection\nprint("Convolution Layer: Scans image for edges.")\n\n# --- OUTPUT INTERPRETATION ---\n# Conceptual output: The layer acts like a flashlight finding specific shapes.`, description: "Concept of Convolution.", colabUrl: "https://colab.research.google.com/" },
            'm3-t10': { code: `# --- SAMPLE INPUT ---\n# ImageNet Weights\n\n# --- ILLUSTRATION ---\nfrom tensorflow.keras.applications import MobileNetV2\nbase_model = MobileNetV2(weights='imagenet', include_top=False)\nprint("Pre-trained MobileNet loaded.")\n\n# --- OUTPUT INTERPRETATION ---\n# Status: Loaded.\n# We borrowed a brain that already knows how to see!`, description: "Loading a pre-trained model for Transfer Learning.", colabUrl: "https://colab.research.google.com/" },
            'm3-t11': { code: `# --- SAMPLE INPUT ---\n# Folders: healthy, rust, blight\n\n# --- ILLUSTRATION ---\nimport os\n# Mock structure\nfolders = ['healthy', 'rust', 'blight']\nfor f in folders:\n    print(f"Found class folder: /dataset/{f}")\n\n# --- OUTPUT INTERPRETATION ---\n# Lists the 3 classes we will train on.`, description: "Dataset organization check.", colabUrl: "https://colab.research.google.com/" },
            'm3-t12': { code: `# --- SAMPLE INPUT ---\n# Image containing a 'weed'\n\n# --- ILLUSTRATION ---\ndef yolo_mock(image):\n    # Mock bounding box output [x, y, w, h, class]\n    return [[50, 50, 20, 30, 'weed']]\nprint("YOLO Detection: Found 1 object.")\n\n# --- OUTPUT INTERPRETATION ---\n# Found 1 object.\n# The coordinates [50, 50...] tell us exactly WHERE the weed is.`, description: "Object Detection output format.", colabUrl: "https://colab.research.google.com/" },
            'm3-t13': { code: `# --- SAMPLE INPUT ---\n# Random Soil Data points\n\n# --- ILLUSTRATION ---\nfrom sklearn.cluster import KMeans\nimport numpy as np\nX = np.random.rand(50, 2)\nkmeans = KMeans(n_clusters=3)\nlabels = kmeans.fit_predict(X)\nprint("Soil Zones Identified:", np.unique(labels))\n\n# --- OUTPUT INTERPRETATION ---\n# Zones: [0 1 2]\n# The field was split into 3 distinct Management Zones.`, description: "Segment field into management zones.", colabUrl: "https://colab.research.google.com/" },
            'm3-t14': { code: `# --- SAMPLE INPUT ---\n# N=10->pH6.5, N=20->pH6.0\n\n# --- ILLUSTRATION ---\nfrom sklearn.linear_model import LinearRegression\n# Predict pH based on N\nmodel = LinearRegression()\nmodel.fit([[10], [20]], [6.5, 6.0])\nprint(f"Predicted pH for N=15: {model.predict([[15]])[0]:.1f}")\n\n# --- OUTPUT INTERPRETATION ---\n# Prediction: 6.2\n# Since 15 is halfway between 10 and 20, pH is halfway between 6.5 and 6.0.`, description: "Regression for Soil Properties.", colabUrl: "https://colab.research.google.com/" },
            'm3-t15': { code: `# --- SAMPLE INPUT ---\n# Current N=120, Target=150\n\n# --- ILLUSTRATION ---\ndef calc_nutrient_gap(current_n, target_n):\n    return max(0, target_n - current_n)\n\ngap = calc_nutrient_gap(current_n=120, target_n=150)\nprint(f"Is Nitrogen needed? {gap} kg/ha")\n\n# --- OUTPUT INTERPRETATION ---\n# Needed: 30 kg/ha\n# Simple subtraction logic for fertilizer recommendation.`, description: "Calculate fertilizer requirements logic.", colabUrl: "https://colab.research.google.com/" },
            'm3-t16': { code: `# --- SAMPLE INPUT ---\n# Amount = 100kg\n\n# --- ILLUSTRATION ---\ndef cost_function(fertilizer_amount):\n    return fertilizer_amount * 50 # Rs 50/kg\nprint(f"Cost for 100kg: Rs {cost_function(100)}")\n\n# --- OUTPUT INTERPRETATION ---\n# Cost: Rs 5000\n# Used to optimize budget vs yield.`, description: "Basic cost optimization function.", colabUrl: "https://colab.research.google.com/" },
            'm3-t17': { code: `# --- SAMPLE INPUT ---\n# Moisture=25% (Low), Rain=False\n\n# --- ILLUSTRATION ---\nmoisture = 25\nrain_forecast = False\nif moisture < 30 and not rain_forecast:\n    print("Turn Irrigation ON")\n\n# --- OUTPUT INTERPRETATION ---\n# Output: TURN ON\n# Precision decision prevents water waste.`, description: "Logic for Precision Irrigation.", colabUrl: "https://colab.research.google.com/" },
            'm3-t18': { code: `# --- SAMPLE INPUT ---\n# Temp=30C, Wind=5kmph\n\n# --- ILLUSTRATION ---\ndef calc_ET(temp, wind):\n    return temp * 0.1 + wind * 0.05\nprint(f"Water Loss (mm): {calc_ET(30, 5):.1f}")\n\n# --- OUTPUT INTERPRETATION ---\n# Loss: 3.2 mm\n# We need to replace exactly this amount of water.`, description: "Simplified Evapotranspiration calculation.", colabUrl: "https://colab.research.google.com/" },
            'm3-t19': { code: `# --- SAMPLE INPUT ---\n# Time Series with Annual Pattern\n\n# --- ILLUSTRATION ---\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom statsmodels.tsa.seasonal import seasonal_decompose\n\n# Time Series Decomposition\ndates = pd.date_range(start='1/1/2023', periods=365)\ndata = pd.Series([x + (x%30) for x in range(365)], index=dates)\nresult = seasonal_decompose(data, model='additive', period=30)\nresult.plot()\nplt.show()\n\n# --- OUTPUT INTERPRETATION ---\n# (Plot Window)\n# 4 Graphs appear: Original, Trend (Up), Seasonal (Wiggles), Residual (Noise).`, description: "Visualizing Seasonality & Trend.", colabUrl: "https://colab.research.google.com/" },
            'm3-t20': { code: `# --- SAMPLE INPUT ---\n# Increasing Data Series\n\n# --- ILLUSTRATION ---\nfrom statsmodels.tsa.arima.model import ARIMA\nimport numpy as np\ndata = np.random.rand(50) + np.linspace(0, 10, 50)\nmodel = ARIMA(data, order=(1,1,1))\nfit = model.fit()\nprint(f"Next Forecast: {fit.forecast()[0]:.2f}")\n\n# --- OUTPUT INTERPRETATION ---\n# Forecast value (e.g., 10.2)\n# Predicts the next step in the sequence.`, description: "Forecast simple time series with ARIMA.", colabUrl: "https://colab.research.google.com/" },
            'm3-t21': { code: `# --- SAMPLE INPUT ---\n# Data: [10, 12, 11, 50, 10]\n\n# --- ILLUSTRATION ---\ndata = [10, 12, 11, 50, 10]\nmean = sum(data)/len(data)\nfor x in data:\n    if abs(x - mean) > 20: print(f"Anomaly Detected: {x}")\n\n# --- OUTPUT INTERPRETATION ---\n# Anomaly Detected: 50\n# 50 is too far from the average.`, description: "Simple Anomaly Detection logic.", colabUrl: "https://colab.research.google.com/" },
            'm3-t22': { code: `# --- SAMPLE INPUT ---\n# Today=100, Tomorrow=110\n\n# --- ILLUSTRATION ---\nprice_today = 100\n# Mock prediction\nprice_tomorrow = price_today * 1.1\nprint(f"Sell now? {'No' if price_tomorrow > price_today else 'Yes'}")\n\n# --- OUTPUT INTERPRETATION ---\n# Sell now? No\n# Wait because price is increasing.`, description: "Price trend decision logic.", colabUrl: "https://colab.research.google.com/" },
            'm3-t23': { code: `# --- SAMPLE INPUT ---\n# Base=100, Festival=1.5x\n\n# --- ILLUSTRATION ---\ndemand_base = 100\nfestival_factor = 1.5\nprint(f"Festival Demand: {demand_base * festival_factor}")\n\n# --- OUTPUT INTERPRETATION ---\n# Demand: 150\n# Domain knowledge helps adjust predictions.`, description: "Demand multiplier logic.", colabUrl: "https://colab.research.google.com/" },
            'm3-t24': { code: `# --- SAMPLE INPUT ---\n# A->B->C Connection\n\n# --- ILLUSTRATION ---\nprint("Node A (Oil) -> Node B (Transport) -> Node C (Food Price)")\n\n# --- OUTPUT INTERPRETATION ---\n# Explains causality: Oil prices affect Transport, which affects Food.`, description: "Text representation of a Knowledge Graph.", colabUrl: "https://colab.research.google.com/" },
            'm3-t7': { code: `from tensorflow.keras import layers, models\nmodel = models.Sequential()\nmodel.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(64, 64, 3)))\nmodel.add(layers.MaxPooling2D((2, 2)))\nmodel.summary()\nprint("CNN Feature Extraction Layer Built")`, description: "Build the feature extraction base of a CNN.", colabUrl: "https://colab.research.google.com/" },
            'm3-t13': { code: `from sklearn.cluster import KMeans\nimport numpy as np\nX = np.random.rand(50, 2)\nkmeans = KMeans(n_clusters=3)\nlabels = kmeans.fit_predict(X)\nprint("Soil Zones Identified:", np.unique(labels))`, description: "Segment field into management zones.", colabUrl: "https://colab.research.google.com/" },
            'm3-t15': { code: `def calc_nutrient_gap(current_n, target_n):\n    return max(0, target_n - current_n)\n\ngap = calc_nutrient_gap(current_n=120, target_n=150)\nprint(f"Is Nitrogen needed? {gap} kg/ha")`, description: "Calculate fertilizer requirements logic.", colabUrl: "https://colab.research.google.com/" },
            'm3-t20': { code: `from statsmodels.tsa.arima.model import ARIMA\nimport numpy as np\ndata = np.random.rand(50) + np.linspace(0, 10, 50)\nmodel = ARIMA(data, order=(1,1,1))\nfit = model.fit()\nprint(f"Next Forecast: {fit.forecast()[0]:.2f}")`, description: "Forecast simple time series with ARIMA.", colabUrl: "https://colab.research.google.com/" },

            // --- MODULE 4: Capstone ---
            'm4-t1': { code: `# --- SAMPLE INPUT ---\n# Quality=8, Skill=7\n\n# --- ILLUSTRATION ---\ndef assess_risk(data_quality, team_skill):\n    return (data_quality + team_skill) / 2\n\nrisk = assess_risk(8, 7)\nprint(f"Project Viability Score: {risk}/10")\n\n# --- OUTPUT INTERPRETATION ---\n# Score: 7.5/10\n# Higher is better. >7 is generally safe to proceed.`, description: "Quantify project risks.", colabUrl: "https://colab.research.google.com/" },
            'm4-t4': { code: `# --- SAMPLE INPUT ---\n# File 'dataset.csv' exists\n\n# --- ILLUSTRATION ---\nimport pandas as pd\ntry:\n    # Mock loading\n    # df = pd.read_csv('dataset.csv')\n    print("Dataset Loaded: 1000 rows.")\nexcept:\n    print("Dataset not found. Please upload 'dataset.csv'.")\n\n# --- OUTPUT INTERPRETATION ---\n# Success message confirms the file path is correct.`, description: "Script to validate dataset loading.", colabUrl: "https://colab.research.google.com/" },
            'm4-t10': { code: `# --- SAMPLE INPUT ---\n# Iris-like Data\n\n# --- ILLUSTRATION ---\nimport seaborn as sns\nimport matplotlib.pyplot as plt\nimport pandas as pd\n\n# Pair Plot (Global Relationships)\ndf = pd.DataFrame({\n    'Height': [10, 20, 30, 40],\n    'Width': [5, 10, 15, 20],\n    'Yield': [100, 200, 300, 400],\n    'Disease': ['No', 'No', 'Yes', 'Yes']\n})\nsns.pairplot(df, hue='Disease')\nplt.show()\n\n# --- OUTPUT INTERPRETATION ---\n# (Plot Window)\n# A grid of scatter plots. Orange dots (Disease=Yes) might cluster apart from Blue dots.`, description: "EDA: Pair Plot Analysis.", colabUrl: "https://colab.research.google.com/" },
            'm4-t11': { code: `# --- SAMPLE INPUT ---\n# Val: [1, NaN, 3, 1000]\n\n# --- ILLUSTRATION ---\nimport pandas as pd\nimport numpy as np\ndf = pd.DataFrame({'val': [1, np.nan, 3, 1000]})\n# Remove Outliers (>100)\ndf = df[df['val'] < 100]\n# Fill NaN with mean\ndf = df.fillna(df.mean())\nprint(df)\n\n# --- OUTPUT INTERPRETATION ---\n#    val\n# 0  1.0\n# 2  3.0\n# NaN was filled, 1000 removed.`, description: "Clean data by removing outliers and filling missing values.", colabUrl: "https://colab.research.google.com/" },
            'm4-t14': { code: `# --- SAMPLE INPUT ---\n# Training for 3 Epochs\n\n# --- ILLUSTRATION ---\nprint("Starting Training...")\nfor epoch in range(1, 4):\n    print(f"Epoch {epoch}: Loss = {0.5/epoch:.4f}")\nprint("Training Complete. Model Saved.")\n\n# --- OUTPUT INTERPRETATION ---\n# Loss decreases (0.5 -> 0.25 -> 0.16)\n# This means the model is learning successfully.`, description: "Simulated training loop output.", colabUrl: "https://colab.research.google.com/" },
            'm4-t16': { code: `# --- SAMPLE INPUT ---\n# True=[0,1,1,0], Pred=[0,1,0,0]\n\n# --- ILLUSTRATION ---\nfrom sklearn.metrics import accuracy_score\ny_true = [0, 1, 1, 0]\ny_pred = [0, 1, 0, 0]\nacc = accuracy_score(y_true, y_pred)\nprint(f"Model Accuracy: {acc*100}%")\n\n# --- OUTPUT INTERPRETATION ---\n# Accuracy: 75%\n# 3 out of 4 predictions were correct.`, description: "Validation metrics calculation.", colabUrl: "https://colab.research.google.com/" },
            'm4-t21': { code: `# --- SAMPLE INPUT ---\n# GET /predict\n\n# --- ILLUSTRATION ---\nfrom flask import Flask\napp = Flask(__name__)\n@app.route('/predict')\ndef predict():\n    return {'result': 'Healthy'}\nprint("API Code Ready. Run on server.")\n\n# --- OUTPUT INTERPRETATION ---\n# API Endpoint created.\n# Sending a request to '/predict' returns JSON data.`, description: "Skeleton code for a Flask API.", colabUrl: "https://colab.research.google.com/" },
            'm4-t25': { code: `# --- SAMPLE INPUT ---\n# Final Stats\n\n# --- ILLUSTRATION ---\nprint("Project: Potato Blight Detector")\nprint("Impact: Reduced crop loss by 15%.")\nprint("Status: Deployed & Live.")\n\n# --- OUTPUT INTERPRETATION ---\n# Project Summary.\n# Key metrics (15% reduction) prove business value.`, description: "Final presentation impact summary.", colabUrl: "https://colab.research.google.com/" },

            // --- MODULE 5: Bonus Projects & Deployment ---
            'm5-t1': {
                code: `# --- SAMPLE INPUT ---\n# Code for app.py\n\n# --- ILLUSTRATION ---\nimport streamlit as st\n# Write app file\ncode = """\nimport streamlit as st\nst.title('My AI Agri Project')\nst.write('Hello World!')\n"""\nwith open("app.py", "w") as f:\n    f.write(code)\nprint("App.py created. Run: streamlit run app.py")\n\n# --- OUTPUT INTERPRETATION ---\n# File created.\n# This script generates the web interface code.`,
                description: "Setup Streamlit and Tunnel for Demo.",
                colabUrl: "https://colab.research.google.com/"
            },
            'm5-t2': { code: `# --- SAMPLE INPUT ---\n# Threshold=30, Moisture=25\n\n# --- ILLUSTRATION ---\nclass SmartIrrigation:\n    def __init__(self, threshold=30):\n        self.threshold = threshold\n    def check(self, moisture):\n        return "ON" if moisture < self.threshold else "OFF"\n\nsys = SmartIrrigation()\nprint(f"Pump is {sys.check(25)}")\n\n# --- OUTPUT INTERPRETATION ---\n# Pump is ON\n# Because 25 < 30. Logic holds.`, description: "IoT Logic for Smart Irrigation.", colabUrl: "https://colab.research.google.com/" },
            'm5-t3': { code: `# --- SAMPLE INPUT ---\n# POST Image -> Risk\n\n# --- ILLUSTRATION ---\nfrom flask import Flask\napp = Flask(__name__)\nprint("Flask API defined.")\n# @app.route defines the URL path\n\n# --- OUTPUT INTERPRETATION ---\n# Defines the backend server structure.`, description: "Flask API Endpoint Skeleton.", colabUrl: "https://colab.research.google.com/" },
            'm5-t4': { code: `# --- SAMPLE INPUT ---\n# Date/Price Data\n\n# --- ILLUSTRATION ---\nimport pandas as pd\nimport plotly.express as px\ndf = pd.DataFrame({'Date': ['2023-01', '2023-02'], 'Price': [100, 120]})\nfig = px.line(df, x='Date', y='Price', title='Market Trends')\nfig.show()\n\n# --- OUTPUT INTERPRETATION ---\n# (Interactive Plot)\n# Display a line chart you can zoom and hover over.`, description: "Plotly Dashboard Basics.", colabUrl: "https://colab.research.google.com/" },
            'm5-t5': { code: `# --- SAMPLE INPUT ---\n# [N,P,K] values\n\n# --- ILLUSTRATION ---\nfrom sklearn.ensemble import RandomForestRegressor\n# X=[N, P, K], y=Yield\nX = [[10,20,30], [12,22,32]]\ny = [50, 55]\nmodel = RandomForestRegressor().fit(X, y)\nprint(f"Pred: {model.predict([[11,21,31]])[0]:.2f}")\n\n# --- OUTPUT INTERPRETATION ---\n# Pred: 52.50\n# Interpolated value logic.`, description: "Soil Nutrient Regression Model.", colabUrl: "https://colab.research.google.com/" },
            'm5-t6': { code: `# --- SAMPLE INPUT ---\n# Image Field.jpg\n\n# --- ILLUSTRATION ---\n# import torch\n# model = torch.hub.load('ultralytics/yolov5', 'yolov5s')\nprint("YOLO Usage:\nresults = model('field.jpg')\nresults.show()")\n\n# --- OUTPUT INTERPRETATION ---\n# Shows commands to run Object Detection.`, description: "Weed Detection Inference Logic.", colabUrl: "https://colab.research.google.com/" },
            'm5-t7': { code: `# --- SAMPLE INPUT ---\n# Redness = 160\n\n# --- ILLUSTRATION ---\n# Maturity based on Redness\ndef grade_fruit(r_channel_mean):\n    return "Ripe" if r_channel_mean > 150 else "Raw"\nprint(grade_fruit(160))\n\n# --- OUTPUT INTERPRETATION ---\n# Ripe\n# 160 > 150, so the apple is red enough.`, description: "Fruit Grading Algorithm.", colabUrl: "https://colab.research.google.com/" },
            'm5-t8': { code: `# --- SAMPLE INPUT ---\n# Target=25, Current=20\n\n# --- ILLUSTRATION ---\ntarget_temp = 25\ncurrent_temp = 20\nerror = target_temp - current_temp\nadjustment = error * 0.5 # Proportional term\nprint(f"Heater Intensity: {adjustment}")\n\n# --- OUTPUT INTERPRETATION ---\n# Intensity: 2.5\n# Turn up heat because 20 < 25.`, description: "Greenhouse Temp Control Logic.", colabUrl: "https://colab.research.google.com/" },
            'm5-t9': { code: `# --- SAMPLE INPUT ---\n# Coords (10, 10)\n\n# --- ILLUSTRATION ---\nimport math\ndef get_arm_angles(x, y):\n    theta = math.atan2(y, x)\n    return math.degrees(theta)\nprint(f"Base Angle: {get_arm_angles(10, 10)} degrees")\n\n# --- OUTPUT INTERPRETATION ---\n# Angle: 45.0 degrees\n# Points diagonally to reach (10,10).`, description: "Robotic Arm Angle Calculation.", colabUrl: "https://colab.research.google.com/" },
            'm5-t10': { code: `# --- SAMPLE INPUT ---\n# Grid Map 3x3\n\n# --- ILLUSTRATION ---\ngrid = [[0,1,0], [0,0,0], [1,0,0]] # 1=Obstacle\nprint("Pathfinding started...")\nprint("Avoiding [0,1] and [2,0]...")\n\n# --- OUTPUT INTERPRETATION ---\n# Simulates drone avoiding obstacles.`, description: "Drone Navigation Grid.", colabUrl: "https://colab.research.google.com/" },
            'm5-t11': { code: `# --- SAMPLE INPUT ---\n# HR=40 (Low)\n\n# --- ILLUSTRATION ---\nfrom sklearn.ensemble import IsolationForest\n# Activity Data: [Steps, HeartRate]\nX = [[100, 60], [110, 65], [10, 40]] # Last one is anomalous\nclf = IsolationForest().fit(X)\npred = clf.predict([[10, 40]])\nprint(f"Status: {'Anomaly' if pred[0]==-1 else 'Normal'}")\n\n# --- OUTPUT INTERPRETATION ---\n# Status: Anomaly\n# The behavior is very different from the others.`, description: "Livestock Anomaly Detection.", colabUrl: "https://colab.research.google.com/" },
            'm5-t12': { code: `# --- SAMPLE INPUT ---\n# API Response JSON\n\n# --- ILLUSTRATION ---\nimport requests\n# response = requests.get('https://api.weather.com/v1/forecast')\nprint("Fetching Weather API Data... [200 OK]")\n\n# --- OUTPUT INTERPRETATION ---\n# Successful connection simulation.`, description: "Weather API Integration.", colabUrl: "https://colab.research.google.com/" },
            'm5-t13': { code: `# --- SAMPLE INPUT ---\n# Last Crop: Mustard\n\n# --- ILLUSTRATION ---\nhistory = ["Wheat", "Mustard"]\ndef recommend(history):\n    if history[-1] == "Mustard": return "Legumes"\n    return "Wheat"\nprint(f"Next Crop: {recommend(history)}")\n\n# --- OUTPUT INTERPRETATION ---\n# Legumes\n# Nitrogen fixer needed after Mustard.`, description: "Crop Rotation Rules Engine.", colabUrl: "https://colab.research.google.com/" },
            'm5-t14': { code: `# --- SAMPLE INPUT ---\n# Q: Treat rust?\n\n# --- ILLUSTRATION ---\ncontext = "Rust is fungal..."\nprint(f"Bot Answer: Based on context '{context}', apply fungicides.")\n\n# --- OUTPUT INTERPRETATION ---\n# Retrieves answer from Knowledge Base.`, description: "Simple Chatbot Logic.", colabUrl: "https://colab.research.google.com/" },
            'm5-t15': { code: `# --- SAMPLE INPUT ---\n# NIR=0.6, Red=0.1\n\n# --- ILLUSTRATION ---\n# NDVI Calc\nnir = 0.6\nred = 0.1\nndvi = (nir - red) / (nir + red)\nprint(f"Vegetation Index: {ndvi:.2f}")\n\n# --- OUTPUT INTERPRETATION ---\n# Index: 0.71\n# Healthy vegetation.`, description: "Satellite NDVI Calculation.", colabUrl: "https://colab.research.google.com/" },
            'm5-t16': { code: `# --- SAMPLE INPUT ---\n# Costs: [10, 20, 15]\n\n# --- ILLUSTRATION ---\ncosts = [10, 20, 15]\nroutes = ["A", "B", "C"]\nbest_route = routes[costs.index(min(costs))]\nprint(f"Cheapest Route: {best_route}")\n\n# --- OUTPUT INTERPRETATION ---\n# Route A (Cost 10)\n# Simple minimization logic.`, description: "Supply Chain Optimization.", colabUrl: "https://colab.research.google.com/" },
            'm5-t17': { code: `# --- SAMPLE INPUT ---\n# pH=6.0 (Normal)\n\n# --- ILLUSTRATION ---\nph = 6.0\nif ph < 5.5: print("Add Base")\nelif ph > 6.5: print("Add Acid")\nelse: print("Nutrients Optimal")\n\n# --- OUTPUT INTERPRETATION ---\n# Nutrients Optimal\n# pH is within healthy range (5.5-6.5).`, description: "Hydroponics Monitoring Logic.", colabUrl: "https://colab.research.google.com/" },
            'm5-t18': { code: `# --- SAMPLE INPUT ---\n# Image Blobs\n\n# --- ILLUSTRATION ---\n# import cv2\n# blobs = detector.detect(gray)\nprint("Detected 45 Pests.")\n\n# --- OUTPUT INTERPRETATION ---\n# Computer Vision counts distinct objects.`, description: "Pest Counting Logic.", colabUrl: "https://colab.research.google.com/" },
            'm5-t19': { code: `# --- SAMPLE INPUT ---\n# Nitrate=10, pH=7\n\n# --- ILLUSTRATION ---\nnitrate = 10\nph = 7\nwqi = nitrate * 0.5 + ph * 0.5\nprint(f"Water Quality Index: {wqi}")\n\n# --- OUTPUT INTERPRETATION ---\n# WQI: 8.5\n# Weighted average score.`, description: "Water Quality Calculation.", colabUrl: "https://colab.research.google.com/" },
            'm5-t20': { code: `# --- SAMPLE INPUT ---\n# Sowing Check\n\n# --- ILLUSTRATION ---\nschedule = ["Week1: Sow", "Week2: Water"]\nfitness = 0.9\nprint(f"Schedule Fitness: {fitness}")\n\n# --- OUTPUT INTERPRETATION ---\n# 0.9 (High)\n# Schedule meets most constraints (Optimization).`, description: "Genetic Algo Skeleton.", colabUrl: "https://colab.research.google.com/" },
            'm5-t21': { code: `# --- SAMPLE INPUT ---\n# Vibration Data\n\n# --- ILLUSTRATION ---\nvibration = [0.1, 0.2, 0.9, 0.1]\n# 0.9 is high vibration -> Warning\nif max(vibration) > 0.8: print("⚠️ Maintenance Required")\n\n# --- OUTPUT INTERPRETATION ---\n# ⚠️ Maintenance Required\n# Spike in vibration indicates machine fault.`, description: "Predictive Maintenance Logic.", colabUrl: "https://colab.research.google.com/" }
        };
    }
}

const labSystem = new LabSystem();


window.labSystem = labSystem;
